apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    fdk.service: sso
  name: sso
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: sso
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        fdk.service: sso
    spec:
      containers:
      - env:
        - name: NAMESPACE
          valueFrom:
            secretKeyRef:
              name: common-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: NAMESPACE
        - name: KEYCLOAK_USER
          valueFrom:
            secretKeyRef:
              name: sso-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: KEYCLOAK_USER
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sso-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: KEYCLOAK_PASSWORD
        - name: PROXY_ADDRESS_FORWARDING
          valueFrom:
            secretKeyRef:
              name: sso-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: KEYCLOAK_PROXY_ADDRESS_FORWARDING
        - name: DB_VENDOR
          valueFrom:
            secretKeyRef:
              name: sso-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: DB_VENDOR
        - name: DB_ADDR
          valueFrom:
            secretKeyRef:
              name: sso-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: DB_ADDR
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: sso-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: DB_DATABASE
        - name: DB_SCHEMA
          valueFrom:
            secretKeyRef:
              name: sso-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: DB_SCHEMA
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-{{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
              key: PASSWORD
        name: sso
        image: {{ required "Missing value DOCKER_IMAGE_NAME" .Values.DOCKER_IMAGE_NAME }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: {{ required "Missing value SSO_MEMORY" .Values.SSO_MEMORY | quote }}
      restartPolicy: Always
status: {}
