apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    fdk.service: sso
  name: sso
  namespace: {{ required "Missing value NAMESPACE" .Values.NAMESPACE }}
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9990"
      port: 9990
      targetPort: 9990
  selector:
    fdk.service: sso
status:
  loadBalancer: {}
