apiVersion: v1
kind: Service
metadata:
  labels:
    fdk.service: sso
  name: sso
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    fdk.service: sso
